spring.application.name=ContractWatcher.Monitoring
spring.config.import=optional:file:.env[.properties]

server.port=${MONITORING_PORT:8080}

spring.datasource.url=${MONITORING_DATABASE_URL}
spring.datasource.username=${MONITORING_DATABASE_USER}
spring.datasource.password=${MONITORING_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=monitoring

spring.flyway.default-schema=monitoring
spring.flyway.schemas=monitoring
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

logging.level.org.flywaydb=WARN
